sudo: required
dist: trusty

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

notifications:
  email: false

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run es-check
